# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 24444b20b04b96ba9e7f406f06c8ed04b317c61dd1381b63de8e7eabdbdac8617d2571ed483c93c60e3397c5c7f1b140e81c6ca193b54ac6ad78b3e6511b0f05

test:
  secret_key_base: d2905353ffe58e1016d8944eb96afd4fb465f19a824ebc9ddb3e42d1a878f4ba4baf5ace07d5012ece8c575296ca0283d51cec91a816deffade79c48c019d07f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
